image: docker:1.11.2

services:
  - docker:dind

stages:
  - test
  - build
  - deploy

variables:
  REGISTRY: registry.gitlab.com
  CONTAINER_RELEASE_IMAGE: $REGISTRY/introcept/paale-dai:latest

test:
  stage: test
  script:
    - docker build -t paale-dai -f .docker/node/Dockerfile .
    - docker run -v $PWD:/var/www/paale-dai paale-dai npm install
    - docker run -v $PWD:/var/www/paale-dai paale-dai npm test

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY
    - docker build -t $CONTAINER_RELEASE_IMAGE  -f .docker/node/Dockerfile-production .
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

deploy:
  stage: deploy
  script:
    - apk add --update --no-cache bash
    - bash ./deploy
  only:
    - master