#!/bin/bash

curl -L https://download.getcarina.com/carina/latest/$(uname -s)/$(uname -m)/carina -o carina
mv carina /bin/carina
chmod u+x /bin/carina

eval $(carina env paale-dai)

# check if logged in
docker info

# run node application container
docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY
docker pull $CONTAINER_RELEASE_IMAGE
docker rm --force node_application || true # ingore exit code if no container exists
docker run --env GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID \
    --env GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET \
    --env JWT_PRIVATE_KEY="$JWT_PRIVATE_KEY" \
    --env JWT_PUBLIC_KEY="$JWT_PUBLIC_KEY" \
    -d -p 80:80 --name=node_application --restart=always $CONTAINER_RELEASE_IMAGE

#check running containers
docker ps

#some time for the application to start before the health-check
sleep 2

# health check; this will fail if application is not running
curl -sSf http://auth.introcept.co/health-check
